name: nostr_place
description: "A Nostr-based collaborative pixel canvas - r/place clone with PoW cooldown"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.9.0

workspace:
  - packages/pixel_repository
  - packages/nostr_client

dependencies:
  bloc: ^9.1.0
  equatable: ^2.0.7
  flame: ^1.34.0
  flame_bloc: ^1.12.19
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_colorpicker: ^1.1.0
  flutter_localizations:
    sdk: flutter
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  intl: any
  meta: ^1.16.0
  nostr_client:
  pixel_repository:

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
