name: nostr_canvas
description: "A Nostr-based collaborative pixel canvas - r/place clone with PoW cooldown"
publish_to: 'none'
version: 0.1.1+1

environment:
  sdk: ^3.9.0

workspace:
  - packages/auth_repository
  - packages/pixel_repository
  - packages/nostr_client
  - packages/relay_settings_repository

dependencies:
  auth_repository:
  bloc: ^9.1.0
  equatable: ^2.0.7
  flame: ^1.34.0
  flame_bloc: ^1.12.19
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  hydrated_bloc: ^10.1.1
  intl: any
  meta: ^1.16.0
  nes_ui: ^0.27.0
  nostr: ^1.5.0
  nostr_client:
  pixel_repository:
  relay_settings_repository:
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
